<a href="https://colab.research.google.com/github/MarianoBarciela/Comisi-n-74235-Data-Science-I-/blob/main/Clase3/Clase_3_practica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Clase 3 Práctica 🧠

In [2]:
import numpy as np

arr = np.arange(12)
print (arr)
arr_reshape = arr.reshape((4,3))
print (arr_reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
