<a href="https://colab.research.google.com/github/MarianoBarciela/Comisi-n-74235-Data-Science-I-/blob/main/Clase3/Clase_3_practica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Clase 3 Numpy y pandas Práctica 🧠

In [2]:
import numpy as np

arr = np.arange(12)
print (arr)
arr_reshape = arr.reshape((4,3))
print (arr_reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [3]:
import numpy as np

# Crear dos arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenar los arrays horizontalmente (por defecto)
arr_concatenated = np.concatenate((arr1, arr2))

print(arr_concatenated)


[1 2 3 4 5 6]


In [4]:
import numpy as np

# Crear un array de 9 elementos
arr = np.arange(9)

# Dividir el array en 3 subarrays
arr_split = np.split(arr, 3)

print(arr_split)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [24]:
import numpy as np

array_numeros= np.random.randint(0,100,size=10)  # numeros randoms lista del o al 100 y cantidad
print ('array numeros:',array_numeros)

media= np.mean(array_numeros)       # media
print('media:',media)

arr_reshape= array_numeros.reshape(5,2)   # reshape
print(arr_reshape)

array numeros: [12 13 63 30 65 61 25 72 57 95]
media: 49.3
[[12 13]
 [63 30]
 [65 61]
 [25 72]
 [57 95]]


In [43]:
import numpy as np

array_numeros= np.random.randint(12,900,20)
print(array_numeros)
media_numeros= np.median(array_numeros)
print('Media:',media_numeros)


[612 604 765 718  77 450 411 394 507 708 892 580  95 580 813 686 372 890
 149 765]
Media: 592.0
